# update version of dependencies on chrome-extensions
version: 2
updates:
  # update npm dependencies on chrome-extensions/open-slideshare-in-iframe
  - package-ecosystem: "npm"
    directory: "/ws/chrome-extensions/open-slideshare-in-iframe"
    schedule:
      interval: "weekly"
    labels:
      - "npm deps"
    # https://docs.github.com/ja/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups
    groups:
      eslint:
        patterns:
          - "@typescript-eslint*"
          - "eslint"


  # update github-actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
