INCLUDE /base-tools/Dockerfile.base

# install codeql-cli
# https://docs.github.com/ja/code-security/codeql-cli/using-the-codeql-cli/getting-started-with-the-codeql-cli
# https://docs.github.com/ja/code-security/codeql-cli/using-the-codeql-cli/about-the-codeql-cli#github-codeql-%E3%81%AE%E3%83%A9%E3%82%A4%E3%82%BB%E3%83%B3%E3%82%B9%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6
# download and unzip to system widely from 
RUN mkdir -p /usr/local/src && cd /usr/local/src \
    && sudo curl -fsSL -o codeql-linux64.zip https://github.com/github/codeql-cli-binaries/releases/download/v2.13.1/codeql-linux64.zip \
    && sudo unzip codeql-linux64.zip -d /usr/local \
    && sudo ln -s /usr/local/codeql/codeql /usr/local/bin/codeql \
    ;
