version: "3"

services:
  dev:
    build:
      context: ../../
      dockerfile: ./ws/stable-diffusion-webui/Dockerfile
      args:
        UID: $UID
        GID: $GID
        USERNAME: $USERNAME
        HOMEDIR: $HOMEDIR
        DOCKER_GID: $DOCKER_GID
    command: sleep infinity
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    tty: true
    volumes:
      - type: bind
        source: ../../
        target: /work
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: ~/.config/gh
        target: ${HOMEDIR}/.config/gh
      # https://code.visualstudio.com/remote/advancedcontainers/persist-bash-history
      - type: volume
        source: commandhistory
        target: /commandhistory

volumes:
  commandhistory:
