FROM golang:1.21 AS go-bin

INCLUDE /base-tools/Dockerfile.base

COPY --from=go-bin /usr/local/go /usr/local/go

ENV GOPATH="${HOME}/go"
ENV PATH="${GOPATH}/bin:/usr/local/go/bin:${PATH}"
RUN go install -v golang.org/x/tools/cmd/goimports@latest \
    && go install -v golang.org/x/tools/gopls@latest \
    && go install -v github.com/go-delve/delve/cmd/dlv@latest \
    && go install -v github.com/ramya-rao-a/go-outline@latest \
    && go install -v github.com/posener/complete/v2/gocomplete@latest \
    ;
