MAKEFILE_DIR := $(dir $(abspath $(firstword $(MAKEFILE_LIST))))

include ../../base-tools/dockerfile.mk

.PHONY: open-slideshare-in-iframe
open-slideshare-in-iframe:
	@$(MAKE) -C open-slideshare-in-iframe
