name: Auto Assign PR

on:
  pull_request:
    types:
      - opened
      - reopened

jobs:
  inspect_actor_is_bot:
    runs-on: ubuntu-latest
    outputs:
      is_bot: ${{ steps.actor_is_bot.outputs.is_bot }}
    steps:
      - uses: air-hand/common-actions/inspect_actor@main
        id: actor_is_bot
        with:
          github_event_payload: ${{ toJSON(github.event) }}

  add_assignees:
    needs: inspect_actor_is_bot
    if: ${{ ! fromJSON(needs.inspect_actor_is_bot.outputs.is_bot) }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions-ecosystem/action-add-assignees@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          assignees: ${{ github.actor }}
