name: Auto Assign PR

on:
  pull_request:
    types:
      - opened
      - reopened

permissions:
  pull-requests: write

jobs:
  add_assignees:
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-add-assignees@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          assignees: ${{ github.actor }}
