name: dependabot auto-merge on chrome-extensions
on:
  pull_request:
    paths:
      - "ws/chrome-extensions/**"

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge-by-dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Fetch dependabot-metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout for local action
        uses: actions/checkout@v5

      - name: Generate token
        id: generate-token
        if: ${{ steps.metadata.outputs.update-type == 'version-update:semver-minor' || steps.metadata.outputs.update-type == 'version-update:semver-patch' }}
        uses: ./.github/actions/generate-token-by-app
        with:
          # register Dependabot secrets.
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Auto review and merge
        if: ${{ steps.metadata.outputs.update-type == 'version-update:semver-minor' || steps.metadata.outputs.update-type == 'version-update:semver-patch' }}
        uses: ./.github/actions/auto-review-merge
        with:
          pr_url: ${{ github.event.pull_request.html_url }}
          github_token: ${{ steps.generate-token.outputs.token }}
