# 
on:
  push:
    paths:
      - '.github/workflows/aws-test.yaml'
      - '**/terraform/**'

# https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services#adding-the-identity-provider-to-aws
env:
  S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
  ROLE_TO_ASSUME_ARN: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-role-for-my-works
  AWS_REGION: ap-northeast-1

permissions:
  id-token: write
  contents: read

jobs:
  inspect-workdir:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: List files in the working directory
        run: |
          ls -R ${{ github.workspace }}
      - name: List files in the working directory
        run: |
          ls -R ${{ github.workspace }}/terraform
  plan:
    env:
      WORKING_DIRECTORY: ws/github/terraform/aws-self-actions-runner
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIRECTORY }}
    steps:
      - uses: actions/checkout@v4
      - uses: aquaproj/aqua-installer@v2
        with:
          working_directory: ${{ env.WORKING_DIRECTORY }}

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.ROLE_TO_ASSUME_ARN }}
          aws-region: ${{ env.AWS_REGION }}
          role-duration-seconds: 900

      - run: |
          aws sts get-caller-identity

      - name: init
        run: |
          terraform init --bucket-config="bucket=${{ secrets.S3_BUCKET_NAME }}"
      - name: test
        run: |
          terraform fmt -recursive -check
      - name: plan
        run: |
          terraform plan
