on:
  push:
    paths:
      - "ws/chrome-extensions/**"
      - "ws/security/easybuggy-codeql/**"
  pull_request:
    paths:
      - "ws/chrome-extensions/**"
      - "ws/security/easybuggy-codeql/**"

jobs:
  Build-And-Run:
    runs-on: ubuntu-latest
    strategy:
      #fail-fast: true
      matrix:
        workdir:
          - "ws/chrome-extensions"
          - "ws/security/easybuggy-codeql"
    defaults:
      run:
        working-directory: ${{ matrix.workdir }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: install devcontainer/cli
        run: npm install -g @devcontainers/cli

      - name: build devcontainer
        run: devcontainer up --workspace-folder=./ --remove-existing-container
